[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install"]

[phases.build]
cmds = ["cd ../.. && cd apps/api && pnpm run build"]

[start]
cmd = "pnpm run start"
